# Generated by Django 4.2.20 on 2025-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeioRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIX', 'PIX'), ('Cartao_de_Credito', 'Cartão de Crédito')], max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_conta', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
