# Generated by Django 4.2.20 on 2025-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('senha', models.CharField(max_length=9)),
                ('celular', models.CharField(max_length=127)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='user_users__name_b89853_idx'), models.Index(fields=['email'], name='user_users__email_a83902_idx'), models.Index(fields=['celular'], name='user_users__celular_df3dff_idx'), models.Index(fields=['senha'], name='user_users__senha_e16db4_idx')],
            },
        ),
    ]
