# Generated by Django 4.2.20 on 2025-08-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=127)),
                ('publicadora', models.CharField(max_length=127)),
                ('preco', models.CharField(max_length=7)),
                ('data_lancamento', models.DateField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.user_vendedor')),
            ],
            options={
                'indexes': [models.Index(fields=['nome'], name='produto_jog_nome_c15bf3_idx'), models.Index(fields=['publicadora'], name='produto_jog_publica_5f30f5_idx'), models.Index(fields=['data_lancamento'], name='produto_jog_data_la_60ab2b_idx')],
            },
        ),
    ]
