# Generated by Django 4.2.20 on 2025-08-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meio_recebimento', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_vendedor',
            fields=[
                ('users_cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.users_cliente')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('meio_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meio_recebimento.meiorecebimento')),
            ],
            options={
                'indexes': [models.Index(fields=['cnpj'], name='vendedor_us_cnpj_4c246b_idx'), models.Index(fields=['meio_recebimento'], name='vendedor_us_meio_re_ef1da9_idx')],
            },
            bases=('user.users_cliente',),
        ),
    ]
